### ISSUE TITLE
Knative Serving queue-proxy does not start when runtimeClassName wasmedge-v1 specified

### ISSUE THREAD

**Issue by KaiWalter** [ZEISS/enterprise-wasm#35]
When deploying a WasmEdge module with Knative Serving:

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: http-server
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      runtimeClassName: wasmedge-v1
      timeoutSeconds: 1
      containers:
        - name: http-server
          image: { will be replaced by deployment script }
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
```

the `queue-proxy` container of the created pod shows:

```
failed to create containerd task: failed to start shim: start failed:  io.containerd.wasmedge.v1: Other("failed to setup namespaces: Other: could not open network namespace /proc/0/ns/net: No such file or directory (os error 2)")  : exit status 1: unknown 
```

---

Already adjusted:

```
kubectl patch configmap/config-features -n knative-serving --type merge --patch '{"data":{"kubernetes.podspec-runtimeclassname":"enabled"}}';
```

based on <https://wasmedge.org/docs/develop/deploy/kubernetes/knative/>
